# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4dd713b6e2128cd9a84f342ad93d3006ade979f349294d471b1921c54981922f887012ae33dd3f873cd6384aec007f9819379b6aa94e4c1d9987535d4d0c4ec

test:
  secret_key_base: 3bf655b6efb6ebf1f33cbc4433e859658b51e42c25481d3169884ca74d09e79441f7573ce1bd9349fe9cf10af112ca4472aa0f6d4994996c70e5a8677d99d902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
